### PR TITLE
add Kopano to the list of organizations

### PR DESCRIPTION
**Pull request by fbartels**
Hi,
at Kopano we are also true believers of open source and therefore have all our software projects available with an agpl license. While we do sell a subscription for our software (which gives access to qa'ed software packages and package repositories as well as support) you can download nightly releases and run it with the same feature set as our customers do.

### CODE REVIEW

**Comment by agarrharr** [comment]
The url isn't quite right. It's currently `https://https://kopano.io/`. I think it should be `https://kopano.io/`.

**Comment by fbartels** [comment]
oh, indeed. url is fixed now.

**Comment by Mayeu** [comment]
Hello :wave:

Thank you for taking the time to open this pull request :pray: (and thank you also @agarrharr for jumping in!)

I have two feedback on this PR.

First, can we try to reduce the size of the description while retaining the most important part? It's way bigger than all the others and feel kind of weird in the middle of one or two lines description. On [Kopano.com](https://kopano.com), I see that the tagline is: "Your Data, Your Terms. In control of your data with Kopano’s self-hosted collaboration suite.", maybe that would be our shorter alternative :)

Second, I think we should instead link to [Kopano.com](https://kopano.com/) which present the tools in a more user-friendly way, and still state clearly the 100% Libre nature of the project.

What both of you (@fbartels, @agarrharr) think about those changes?

**Comment by Mayeu** [comment]
@agarrharr I agree with you, but I fear that we are slowly getting into the bikeshedding territory :smile: 

So I let @fbartels chose the one he thinks is best, and will merge it. We will still have the possibility to merge new change again later :slightly_smiling_face:

**Pull request merged**
